# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Venkat
tagline:             Computer Science, Programming, Philosophy and Life
url:                 http://venustus.in
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Venkata Rao Pedapati
  url:               https://twitter.com/venustus
  email:             venkat.pedapati@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/venustus/venustus.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

